### ISSUE TITLE
TypeError: normphe() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by chaimol** [YuetongXU/CropGBM#2]
I am run the  command `cropgbm -o gbm_result -pp --phe-plot --phefile-path phefile.txt --phefile-sep ',' --phe-name DTT --ppgroupfile-path phefile.txt --ppgroupfile-sep ',' --ppgroupid-name paternal_line --phe-norm` base your demo data. but have one errinfo 
```
Traceback (most recent call last):
  File "/share/home/chai/.local/bin/cropgbm", line 8, in <module>
    sys.exit(main())
  File "/share/home/chai/.local/lib/python3.8/site-packages/cropgbm/main.py", line 352, in main
    Pp.plot_phenodist_scatter(gphe_data, groupname_list, spf, user_params)
  File "/share/home/chai/.local/lib/python3.8/site-packages/cropgbm/Preprocessed_Pheno.py", line 72, in plot_phenodist_scatter
    normphe_data = normphe(group_data['phe'], spf + '_group' + str(group_name), user_params)
TypeError: normphe() takes 2 positional arguments but 3 were given
```
I have checked your code of `Preprocessed_Pheno.py`, 
Line43 `normphe` function only need 2 arguments, but your use it in Line 72, `normphe_data = normphe(group_data['phe'], spf + '_group' + str(group_name), user_params)` provide 3 arguments. 
Ｉhope you can debug it.

**Comment by ChIPseq** [comment]
I have encountered exactly the same problem as you

**Comment by YuetongXU** [comment]
Sorry, this was caused by the upgrade of dependency versions. It has now been modified. Thank you for your suggestion!
